<#
    
    Citrix.NetScaler module initialization script
    
    For the latest code, instructions, and information, please reference http://github.com/RamblingCookieMonster/Citrix.NetScaler     

#>

#Define global variables
Remove-Variable NSSession -Scope Global -ErrorAction SilentlyContinue -Force
Remove-Variable NSEnumeration -Scope Global -ErrorAction SilentlyContinue -Force
New-Variable NSSession -Value $null -Option AllScope -Scope Global
New-Variable NSEnumeration -Value @() -Option AllScope -Scope Global


#Get the current directory, define subfolders.
$ModPath = Split-Path -Parent $MyInvocation.MyCommand.Definition
$FoldersToImport = "Functions", "AutogenFunctions"

#Get all ps1 files to import
$Files = ForEach ($Folder in $FoldersToImport)
{
    $Folder = Join-Path -Path $ModPath -ChildPath $Folder
        
    #If this folder exists, output the full path
    If (Test-Path $Folder -ErrorAction SilentlyContinue)
    {
        Get-ChildItem $Folder -Filter *.ps1 | Select -ExpandProperty FullName
    }
    #If the folder does not exist, display warning or break, depending on the folder
    Else
    {
        If ($Folder -eq "Functions")
        {
            #The functions folder is required.  Stop importing if it does not exist.
            Throw "Expected '$folder'.  Where is it?"
        }
        Else
        {
            #The autogenerated functions are not required.  Inform the use that they do not exist.
            Write-Warning "AutogenFunctions folder not found.`nOnly imported base functions.`nRead instructions at http://github.com/RamblingCookieMonster/Citrix.NetScaler for details on auto-generating functions`nFor more information, run Get-Help '$ModPath\AutogenFunctions.ps1' -full"
        }
    }
}

#Import the PS1 files
ForEach ($File in $Files)
{
    . "$File"
}

Export-ModuleMember -Function *-*