<#
    
    Citrix.NetScaler module initialization script
    
    For the latest code, instructions, and information, please reference http://github.com/RamblingCookieMonster/Citrix.NetScaler     

#>

#Get the current directory, define subfolders.
    $ModPath = split-path -parent $MyInvocation.MyCommand.Definition
    $foldersToImport = "Functions", "AutogenFunctions"

#Get all ps1 files to import
    $files = foreach($folder in $foldersToImport)
    {
        $folder = Join-Path $ModPath $folder
        
        #If this folder exists, output the full path
        if(test-path $folder -ErrorAction SilentlyContinue)
        {
            Get-ChildItem $folder -Filter *.ps1 | select -ExpandProperty fullname
        }
        #If the folder does not exist, display warning or break, depending on the folder
        else
        {
            if($folder -eq "Functions")
            {
                #The functions folder is required.  Stop importing if it does not exist.
                Throw "Expected '$folder'.  Where is it?"
                Break
            }
            else
            {
                #The autogenerated functions are not required.  Inform the use that they do not exist.
                Write-Warning "AutogenFunctions folder not found.`nOnly imported base functions.`nRead instructions at http://github.com/RamblingCookieMonster/Citrix.NetScaler for details on auto-generating functions`nFor more information, run Get-Help '$ModPath\AutogenFunctions.ps1' -full"
            }
        
        }
    }

#Import the PS1 files
    foreach($file in $files)
    {
        . "$file"
    }

Export-ModuleMember -Function *-*